Single button generation changed to multi-buttons generation
adobe/aem-cf-admin-ui-ext-tpl pull request #13
Opened 2023-04-03 21:54 UTC by naydav

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-04-03 23:49 UTC, askayastha22 commented on src/templates/_shared/stub-app.ejs
> +          <!-- YOUR CUSTOM ROUTES SHOULD BE HERE -->
This HTML comment should be changed to regular comments.
`// TODO: Add additional custom routes here`

2023-04-03 23:51 UTC, askayastha22 commented on src/templates/_shared/stub-extension-registration.ejs
> +              <!-- YOUR ACTION BAR BUTTONS CODE SHOULD BE HERE -->
This HTML comment should be changed to regular comments.
`// TODO: Implement your Action Buttons here`

2023-04-03 23:51 UTC, askayastha22 commented on src/templates/_shared/stub-extension-registration.ejs
> +              <!-- YOUR HEADER BUTTONS CODE SHOULD BE HERE -->
This HTML comment should be changed to regular comments.
`// TODO: Implement your Header Menu buttons here`

2023-04-03 23:54 UTC, askayastha22 requested changes
@naydav Appreciate the use of <%_ for getting rid of whitespaces. Requested some changes.

2023-04-10 16:34 UTC, merged

2023-04-11 01:01 UTC, naydav commented on src/templates/_shared/stub-app.ejs
> +          <!-- YOUR CUSTOM ROUTES SHOULD BE HERE -->
Updated, but without TODO, as it may imply that the generated content is incomplete. However, in our case, the generated content may be sufficient.