Add metadata generation hooks and metadata registration
adobe/aem-cf-admin-ui-ext-tpl pull request #26
Opened 2024-06-26 22:51 UTC by nitinja

## Description

Adds hook to generate and verify metadata from app.config.yaml. Adds the generated metadata to extension registration.

## Related Issue

https://jira.corp.adobe.com/browse/SITES-17283

## Motivation and Context

We would like to generate metadata file from yaml configuration.
This will enable us to convey extension-related config to host, in cases where info from registry not available or feasible.
Generated metadata will be sent to host.

## How Has This Been Tested?

Tested manually by generating extension and local testing using ext param, the main use case.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-06-26 22:54 UTC, nitinja commented
Will be committing tests soon

2024-06-28 02:04 UTC, naydav commented on src/templates/_shared/stub-extension-registration.ejs
> +                'metadata': metadata,
Hi Nitin,

Why did you include this only for the action bar? Perhaps it makes sense to include this for all cases, for example, header declarations or grid columns.

2024-06-28 02:07 UTC, naydav requested changes

2024-06-28 02:07 UTC, naydav commented on src/templates/_shared/stub-extension-registration.ejs
> +                'metadata': metadata,
Hi Nitin,

Why did you include this only for the action bar? Perhaps it makes sense to include this for all cases, for example, header menu declarations.

How it was did in the https://github.com/adobe/aem-cf-editor-ui-ext-tpl/pull/17/files

2024-06-28 18:49 UTC, nitinja commented on src/templates/_shared/stub-extension-registration.ejs
> +                'metadata': metadata,
Fixed it now, its now at top level, for all cases, thanks

2024-06-28 19:30 UTC, nitinja commented
Testing code is committed now. Extension generation manually tested, working fine.

2024-06-28 19:32 UTC, naydav approved these changes

2024-06-28 19:35 UTC, merged